openapi: 3.0.0
info:
  title: HMPPS Integration API
  description: A long-lived API that exposes data from HMPPS systems such as the National Offender Management Information
    System (NOMIS), nDelius (probation system) and Offender Assessment System (OASys), providing a single point
    of entry for consumers.
  version: 0.0.1

paths:
  /persons/{id}:
    get:
      summary: Returns a person.
      description: Get person by ID.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Successfully found a person with the provided ID.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Person"

components:
  schemas:
    Person:
      type: object
      properties:
        firstName:
          type: string
          example: Arthur
        middleName:
          type: string
          example: John
          nullable: true
        lastName:
          type: string
          example: Morgan
        dateOfBirth:
          type: string
          format: date
          example: 1965-12-01
        aliases:
          type: array
          items:
            $ref: "#/components/schemas/Alias"
    Alias:
      type: object
      properties:
        firstName:
          type: string
          example: John
        middleName:
          type: string
          example: Michael
          nullable: true
        lastName:
          type: string
          example: Marston
        dateOfBirth:
          type: string
          format: date
          example: 1965-12-01
